import Link from "next/link";

const services=[["01","Web & E-commerce","Fast, polished websites and online experiences designed to turn attention into action.","WEB"],["02","Custom Software","Purpose-built business applications shaped around your workflow, not the other way around.","SOFTWARE"],["03","AI & Automation","Practical AI and connected workflows that reduce repetitive work and unlock new possibilities.","AI"],["04","Data & Analytics","Clear dashboards and reporting that make operational information easier to understand and use.","DATA"]];

export default function Home(){return <>
<section className="studio-hero"><div className="studio-grid"/><div className="studio-copy"><p className="eyebrow">RABBITEK SOLUTIONS • CREATIVITY HUB</p><h1>Ideas.<br/><span>Technology.</span><br/>Growth.</h1><p>We build websites, custom software and AI-powered digital solutions for businesses ready to work smarter and grow.</p><div className="actions"><Link className="btn" href="/contact">Start a Project →</Link><Link className="outline" href="/work">See Our Work</Link></div><div className="studio-tags"><span>Web Experiences</span><span>Business Systems</span><span>AI Automation</span><span>Analytics</span></div></div><div className="studio-device"><div className="device-glow"/><div className="float-chip chip-ai"><b>✦</b><span>AI<br/><small>Automation</small></span></div><div className="float-chip chip-data"><b>↗</b><span>DATA<br/><small>Insights</small></span></div><div className="studio-laptop"><div className="studio-screen"><div className="appbar"><strong><i>R</i> RABBITEK</strong><span>● SYSTEM ONLINE</span></div><div className="appbody"><aside><b>Overview</b><i/><i/><i/><i/></aside><main><div className="welcome"><small>DIGITAL OPERATIONS</small><strong>Growth Dashboard</strong></div><div className="metric-row"><div><small>PROJECTS</small><b>Active</b><em>↗</em></div><div><small>AUTOMATION</small><b>Running</b><em>✦</em></div><div><small>INSIGHTS</small><b>Live</b><em>●</em></div></div><div className="studio-chart"><div><small>PERFORMANCE</small><b>Business intelligence</b></div><span/><span/><span/><span/><span/><span/><span/></div></main></div></div><div className="studio-base"/></div></div><div className="scroll-note">SCROLL TO EXPLORE <i>↓</i></div></section>
<section className="studio-services"><div className="studio-section-head"><div><p className="eyebrow">WHAT WE DO</p><h2>Digital capability,<br/><span>built around you.</span></h2></div><p>From your first digital presence to connected business systems, we focus on technology that has a clear job to do.</p></div><div className="service-rail">{services.map(([n,t,d,k])=><article key={t}><div className="service-no">{n}</div><div className="service-symbol">{k}</div><h3>{t}</h3><p>{d}</p><Link href="/services">Explore service <b>↗</b></Link></article>)}</div></section>
<section className="studio-belief"><div className="belief-copy"><p className="eyebrow">WHY RABBITEK</p><h2>Start with the <span>problem.</span><br/>Build what matters.</h2><p>Good technology should make something clearer, faster or easier. That is why we begin with the business challenge before deciding what to build.</p><Link href="/about" className="case-link light-link">How we think <b>↗</b></Link></div><div className="belief-flow">{["Understand","Design","Build","Automate","Improve"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span>{i<4&&<i>→</i>}</div>)}</div></section>
<section className="home-work"><div className="studio-section-head"><div><p className="eyebrow">SELECTED WORK</p><h2>Built for the<br/><span>real world.</span></h2></div><p>Digital products shaped around actual operations, customers and decisions.</p></div><div className="featured-work"><article className="feature-card fc-one"><div className="feature-meta"><span>01</span><small>OPERATIONS • CUSTOMER EXPERIENCE</small></div><div className="feature-ui"><div className="feature-window"><b>Kaklinx Auto</b><div><i/><i/><i/></div><em/><em/><em/><em/></div></div><div className="feature-copy"><h3>Kaklinx Auto</h3><p>A connected operations and customer-management experience for a modern car-care business.</p><Link href="/work">View case study ↗</Link></div></article><article className="feature-card fc-two"><div className="feature-meta"><span>02</span><small>ENERGY • DATA • ANALYTICS</small></div><div className="feature-ui"><div className="feature-window"><b>Plant Power Analytics</b><div><i/><i/><i/></div><em/><em/><em/><em/></div></div><div className="feature-copy"><h3>Plant Power Analytics</h3><p>Turning plant energy and operational information into clearer decision-support insights.</p><Link href="/work">View case study ↗</Link></div></article></div><div className="center"><Link className="outline darkoutline" href="/work">Explore Selected Work →</Link></div></section>
<section className="work-cta"><p className="eyebrow">YOUR NEXT IDEA</p><h2>Build smarter.<br/><span>Grow with purpose.</span></h2><p>Tell us what you want to improve, automate or create.</p><Link className="btn" href="/contact">Start a Project →</Link></section>
</>}